ServerName localhost

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 common

# Host :8001 → container :80
<VirtualHost *:80>
  ServerName localhost
  DocumentRoot "/var/www/html"

  <Directory "/var/www/html">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

  <FilesMatch "\.php$">
    SetHandler "proxy:fcgi://php:9000"
  </FilesMatch>

  DirectoryIndex index.php index.html
</VirtualHost>

Listen 443
# Host :8002 → container :443
<VirtualHost *:443>
  ServerName localhost
  DocumentRoot "/var/www/html"

  SSLEngine on
  SSLCertificateFile /usr/local/apache2/conf/certs/localhost.crt
  SSLCertificateKeyFile /usr/local/apache2/conf/certs/localhost.key

  <Directory "/var/www/html">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

  <FilesMatch "\.php$">
    SetHandler "proxy:fcgi://php:9000"
  </FilesMatch>

  DirectoryIndex index.php index.html
</VirtualHost>
