/**
 * FO page objects for the default theme.
 * Re-exports upstream ui-testing symbols (package API still uses legacy names).
 */
export {
  foHummingbirdAboutUsPage as foDefaultAboutUsPage,
  foHummingbirdBestSalesPage as foDefaultBestSalesPage,
  foHummingbirdCartPage as foDefaultCartPage,
  foHummingbirdCategoryPage as foDefaultCategoryPage,
  foHummingbirdCheckoutOrderConfirmationPage as foDefaultCheckoutOrderConfirmationPage,
  foHummingbirdCheckoutPage as foDefaultCheckoutPage,
  foHummingbirdCmsPage as foDefaultCmsPage,
  foHummingbirdContactUsPage as foDefaultContactUsPage,
  foHummingbirdCreateAccountPage as foDefaultCreateAccountPage,
  foHummingbirdDeliveryPage as foDefaultDeliveryPage,
  foHummingbirdGuestOrderTrackingPage as foDefaultGuestOrderTrackingPage,
  foHummingbirdHomePage as foDefaultHomePage,
  foHummingbirdLegalNoticePage as foDefaultLegalNoticePage,
  foHummingbirdLoginPage as foDefaultLoginPage,
  foHummingbirdModalBlockCartPage as foDefaultModalBlockCartPage,
  foHummingbirdModalQuickViewPage as foDefaultModalQuickViewPage,
  foHummingbirdModalWishlistPage as foDefaultModalWishlistPage,
  foHummingbirdMyAccountPage as foDefaultMyAccountPage,
  foHummingbirdMyAddressesCreatePage as foDefaultMyAddressesCreatePage,
  foHummingbirdMyAddressesPage as foDefaultMyAddressesPage,
  foHummingbirdMyCreditSlipsPage as foDefaultMyCreditSlipsPage,
  foHummingbirdMyGDPRPersonalDataPage as foDefaultMyGDPRPersonalDataPage,
  foHummingbirdMyInformationsPage as foDefaultMyInformationsPage,
  foHummingbirdMyMerchandiseReturnsPage as foDefaultMyMerchandiseReturnsPage,
  foHummingbirdMyOrderDetailsPage as foDefaultMyOrderDetailsPage,
  foHummingbirdMyOrderHistoryPage as foDefaultMyOrderHistoryPage,
  foHummingbirdMyReturnDetailsPage as foDefaultMyReturnDetailsPage,
  foHummingbirdMyVouchersPage as foDefaultMyVouchersPage,
  foHummingbirdMyWishlistsPage as foDefaultMyWishlistsPage,
  foHummingbirdMyWishlistsViewPage as foDefaultMyWishlistsViewPage,
  foHummingbirdNewProductsPage as foDefaultNewProductsPage,
  foHummingbirdPasswordReminderPage as foDefaultPasswordReminderPage,
  foHummingbirdPricesDropPage as foDefaultPricesDropPage,
  foHummingbirdProductPage as foDefaultProductPage,
  foHummingbirdSearchResultsPage as foDefaultSearchResultsPage,
  foHummingbirdSecurePaymentPage as foDefaultSecurePaymentPage,
  foHummingbirdSitemapPage as foDefaultSitemapPage,
  foHummingbirdStoresPage as foDefaultStoresPage,
  foHummingbirdTermsAndConditionsOfUsePage as foDefaultTermsAndConditionsOfUsePage,
} from '@prestashop-core/ui-testing';

