# This tests the build for development
name: Cron docker build

on:
  schedule:
    - cron: "0 1 * * *"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  docker-build:
    name: Docker build

    runs-on: ubuntu-26.04

    strategy:
      matrix:
        version:
          - 8.1
        base:
          - apache
          - fpm

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Running latest prestashop with docker
        run: docker compose -f docker/docker-compose.yml --project-directory . build --build-arg VERSION=${{ matrix.version }}-${{ matrix.base }}
